DROP TABLE IF EXISTS kunden,
kunden_import,
kunden_import_runs;
CREATE TABLE IF NOT EXISTS kunden_import (
    id bigserial PRIMARY KEY,
    import_id bigint NOT NULL,
    imported_at timestamptz NOT NULL,
    imported_by text NOT NULL,
    kunde text,
    strasse text,
    plz text,
    ort text,
    telefon text,
    mobil text,
    geburtstag text,
    kennung text,
    start text,
    ende text,
    auftraege text,
    serviceberater text,
    besuchrhythmus text,
    qs_besuch_datum text,
    qs_besuch_art text,
    qs_besuch_historik text,
    qs_besuch_hinweis_1 text,
    qs_besuch_hinweis_2 text
);
CREATE TABLE IF NOT EXISTS kunden (
    kundennummer text PRIMARY KEY,
    nachname text,
    vorname text,
    strasse text,
    hnr text,
    adz text,
    plz text,
    ort text,
    telefon text,
    mobil text,
    geburtstag date,
    kennung text,
    start date,
    ende date,
    auftraege text,
    serviceberater text,
    besuchrhythmus text,
    qs_besuch_datum date,
    qs_besuch_art text,
    qs_besuch_historik date,
    qs_besuch_hinweis_1 text,
    qs_besuch_hinweis_2 text,
    geom geometry(Point, 4326),
    aktiv boolean NOT NULL DEFAULT true,
    gebref_oid text,
    sgb_37_3 boolean NOT NULL DEFAULT false,
    pflegefirma boolean NOT NULL DEFAULT false
);
CREATE TABLE IF NOT EXISTS kunden_import_runs (
    import_id bigint PRIMARY KEY,
    imported_at timestamptz NOT NULL,
    imported_by text NOT NULL,
    merged boolean DEFAULT false,
    inserted_rows int NOT NULL
);